version: '3'
services:
  web:
    image: oj/web:local
    container_name: oj-web
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "6060:80"
    networks:
      - oj
    volumes:
      - ./tmp/log:/var/log/nginx
networks:
  oj:
    driver: bridge
    name: local
    external: true